- name: Build APK
  run: |
    chmod +x gradlew
    ./gradlew clean
    ./gradlew :app:assembleDebug --stacktrace

- name: Find APK
  run: find . -name "*.apk"

- name: Upload APK
  uses: actions/upload-artifact@v4
  with:
    name: app-debug
    path: app/build/outputs/apk/debug/*.apk
